/* Generated By:JavaCC: Do not edit this line. WHILE0Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WHILE0Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int L_WHILE = 5;
  /** RegularExpression Id. */
  int L_IN = 6;
  /** RegularExpression Id. */
  int L_OUT = 7;
  /** RegularExpression Id. */
  int L_VAR = 8;
  /** RegularExpression Id. */
  int L_DO = 9;
  /** RegularExpression Id. */
  int L_BEGIN = 10;
  /** RegularExpression Id. */
  int L_END = 11;
  /** RegularExpression Id. */
  int VAR = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"while\"",
    "\"in\"",
    "\"out\"",
    "\"var\"",
    "\"do\"",
    "\"begin\"",
    "\"end\"",
    "<VAR>",
    "\"(\"",
    "\",\"",
    "\";\"",
    "\")\"",
    "\"=\"",
    "\"+\"",
    "\"1\"",
    "\"0\"",
    "\"!=\"",
  };

}
